# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-01-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('gst', models.IntegerField(max_length=255, null=True)),
            ],
        ),
    ]
