# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-01-04 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
