# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-01-06 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210106_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gst',
            name='user_id',
        ),
    ]
